experiment_prefix: test

model_name: vit_b_16_pretrained
dataset_name: cifar10
height: 224
width: 224
batch_size: 128

checkpoint: ""
use_wandb: True
data_path: /mnt/dataset/pytorch
seed: 666
hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${model_name}-${dataset_name}-${now:%H-%M-%S}
