experiment_name: train_cnn_cifar

batch_size: 128
learning_rate: 0.001
num_epochs: 100
model_name: cnn
dataset_name: cifar10
height: 32
width: 32
checkpoint: ""
use_wandb: True
data_path: /mnt/dataset/pytorch
seed: 666
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${model_name}-${dataset_name}-${now:%H-%M-%S}
